title: "Semipedia"
description: "A pseudo-encyclopedia, of sorts."
baseurl: "/semipedia"
url: "https://semishawn.github.io"
github_username: "semishawn"

future: true

mobile_width: "650px"
tablet_width: "900px"

current_popup: "grand-opening"

collections:
  popups:

  resources:

  semiboys:

  chapters:
    output: true
    permalink: /chapters/:path

  semiterms:
    output: true
    permalink: /semiterms/:path

  semiqueries:
    output: true
    permalink: /semiqueries/:path

plugins:
  - jekyll-minifier

jekyll-minifier:
  compress_css: false
  uglifier_args:
    harmony: true