title: Semipedia
description: A pseudo-encyclopedia, of sorts.
baseurl: "/semipedia"
url: "https://semishawn.github.io"
github_username: semishawn

future: true

collections:
  resources:
  chapters:
    output: true
    permalink: /chapters/:path
  semiterms:
    output: true
    permalink: /semiterms/:path

# plugins:
# - jekyll-feed