title: Semipedia
description: >- # this means to ignore newlines until "baseurl:"
  A pseudo-encyclopedia, of sorts.
baseurl: "/semipedia"
url: "https://semipedia.org"
github_username: semishawn

incremental: true

collections:
  semiterms:
    output: true
    permalink: /semiterms/:path
  table:
    output: true
    permalink: /table/:path

# plugins:
#   - jekyll-feed